---
abstract: 'Run Postgres CLI utilities'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Exporter: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pg-CLI
requires:
  File::Which: 0
  IPC::Run3: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Params::Validate: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Pg-CLI
  repository: git://git.urth.org/Pg-CLI.git
version: 0.11
